# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-1790d89c-4b17-4ea1-9e26-1aba2d095b0e";
      fsType = "btrfs";
    };

  boot.initrd.luks.devices."luks-1790d89c-4b17-4ea1-9e26-1aba2d095b0e".device = "/dev/disk/by-uuid/1790d89c-4b17-4ea1-9e26-1aba2d095b0e";

  fileSystems."/home" =
    { device = "/dev/mapper/luks-1790d89c-4b17-4ea1-9e26-1aba2d095b0e";
      fsType = "btrfs";
      options = [ "subvol=home" ];
    };

  fileSystems."/nix" =
    { device = "/dev/mapper/luks-1790d89c-4b17-4ea1-9e26-1aba2d095b0e";
      fsType = "btrfs";
      options = [ "subvol=nix" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/1EEA-D14B";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
