;;; -*- lexical-binding: t; -*-

;; Clean the slate.
(menu-bar-mode 0)
(tool-bar-mode 0)
(scroll-bar-mode 0)
(column-number-mode 1)

(setq ring-bell-function 'ignore
      inhibit-startup-screen t
      use-short-answers t)

;; Base modifications.
(set-face-attribute 'default nil :height 140)

(which-key-mode 1)

(setq display-line-numbers-type 'relative)
(add-hook 'prog-mode-hook #'display-line-numbers-mode)
(add-hook 'text-mode-hook #'display-line-numbers-mode)
(add-hook 'conf-mode-hook #'display-line-numbers-mode)

;; Apply the theme generated by matugen.
(add-to-list 'custom-theme-load-path "~/.cache/emacs/themes/")
(load-theme 'dankcolors t)

;; Tree-sitter major mode mapping.
(setq treesit-font-lock-level 4)

(setq major-mode-remap-alist
      '((c-mode          . c-ts-mode)
        (c++-mode        . c++-ts-mode)
        (c-or-c++-mode   . c-or-c++-ts-mode)
        (js-mode         . js-ts-mode)
        (javascript-mode . js-ts-mode)
        (python-mode     . python-ts-mode)
        (css-mode        . css-ts-mode)
        (json-mode       . json-ts-mode)
        (html-mode       . html-ts-mode)
        (sh-mode         . bash-ts-mode)
        (conf-toml-mode  . toml-ts-mode)))

(setq auto-mode-alist
      (append '(
                ("\\.rs\\'"                          . rust-ts-mode)
                ("\\.go\\'"                          . go-ts-mode)
                ("/go\\.mod\\'"                      . go-mod-ts-mode)
                ("\\.ts\\'"                          . typescript-ts-mode)
                ("\\.[tj]sx\\'"                      . tsx-ts-mode)
                ("\\.java\\'"                        . java-ts-mode)
                ("\\.toml\\'"                        . toml-ts-mode)
                ("\\.yaml\\|\\.yml\\'"               . yaml-ts-mode)
                ("\\.cmake\\|CMakeLists\\.txt\\'"    . cmake-ts-mode)
                ("Dockerfile.*\\'"                   . dockerfile-ts-mode)
                ("\\.lua\\'"                         . lua-ts-mode)
                ("\\.elixir\\|\\.exs?\\'"            . elixir-ts-mode)
                ("\\.heex\\'"                        . heex-ts-mode)
                ("\\.mli\\'"                         . ocamli-ts-mode)
                ("\\.ml\\'"                          . ocaml-ts-mode)
                ("\\.\\(?:hs\\|hs-boot\\|hsig\\)\\'" . haskell-ts-mode)
                ("\\.lhs\\'"                         . haskell-literate-mode)
                ("\\.kdl\\'"                         . kdl-mode)
                ("\\.nix\\'"                         . nix-ts-mode)
                ("\\.cljs\\'"                        . clojure-ts-clojurescript-mode)
                ("\\.clj[c]?\\'"                     . clojure-ts-mode)
                ("\\.fish\\'"                        . fish-mode)
               )
              auto-mode-alist))

;; Minibuffer completions.
(use-package vertico
  :init
  (vertico-mode 1)
  :custom
  (vertico-cycle t))

;; Fuzzy matching.
(use-package orderless
  :custom
  (completion-styles '(orderless basic))
  (completion-category-defaults nil)
  (completion-category-overrides '((file (styles partial-completion)))))

;; Buffer navigation.
(use-package consult
  :custom
  (consult-async-min-input 1)
  (consult-async-input-throttle 0.1))

;; In-buffer code completion.
(use-package corfu
  :init
  (global-corfu-mode 1)
  :custom
  (corfu-auto t)
  (corfu-auto-delay 0.1)
  (corfu-auto-prefix 2)
  (corfu-cycle t)
  (corfu-preselect 'prompt))

(use-package cape
  :init
  (add-to-list 'completion-at-point-functions #'cape-file))

;; Jump and jump!
(use-package avy
  :custom
  (avy-timeout-seconds 0.3))

;; A nice terminal.
(use-package eat
  :init
  (setq eat-shell (or (executable-find "fish") "/usr/bin/env fish"))
  :custom
  (eat-kill-buffer-on-exit t))

;; Direnv support.
(use-package envrc
  :hook (after-init . envrc-global-mode))

;; Eglot and diagnostics.
(use-package eglot
  :hook ((prog-mode . eglot-ensure)
         (before-save . (lambda ()
           (when (eglot-managed-p)
           (eglot-format-buffer)))))
  :custom
  (eglot-sync-connect nil)
  :config
  (add-to-list 'eglot-server-programs '((nix-mode nix-ts-mode) . ("nixd"))))

(setq flymake-show-diagnostics-at-end-of-line t)

(custom-set-faces
 '(flymake-error ((t (:height 1.0 :weight bold))))
 '(flymake-warning ((t (:height 1.0 :weight bold))))
 '(flymake-note ((t (:height 1.0 :weight bold))))
 '(flymake-error-echo ((t (:height 1.0))))
 '(flymake-warning-echo ((t (:height 1.0)))))

;; Meow keybindings setup.
(defun meow-setup ()
  (setq meow-cheatsheet-layout meow-cheatsheet-layout-qwerty)

  (meow-motion-define-key
   '("j" . meow-next)
   '("k" . meow-prev)
   '("<escape>" . ignore))

  (meow-leader-define-key
   '("d" . xref-find-definitions)
   '("b" . xref-go-back)
   '("r" . xref-find-references)
   '("k" . eldoc-doc-buffer)
   '("a" . eglot-code-actions)
   '("e" . eglot-rename)
   '("=" . eglot-format)
   '("f" . consult-fd)
   '("p" . consult-ripgrep)
   '("s" . consult-buffer)
   '("x" . kill-current-buffer)
   '("g" . avy-goto-char-timer)
   '("t" . eat)
   '("1" . meow-digit-argument)
   '("2" . meow-digit-argument)
   '("3" . meow-digit-argument)
   '("4" . meow-digit-argument)
   '("5" . meow-digit-argument)
   '("6" . meow-digit-argument)
   '("7" . meow-digit-argument)
   '("8" . meow-digit-argument)
   '("9" . meow-digit-argument)
   '("0" . meow-digit-argument)
   '("/" . meow-keypad-describe-key)
   '("?" . meow-cheatsheet))

  (meow-normal-define-key
   '("0" . meow-expand-0)
   '("9" . meow-expand-9)
   '("8" . meow-expand-8)
   '("7" . meow-expand-7)
   '("6" . meow-expand-6)
   '("5" . meow-expand-5)
   '("4" . meow-expand-4)
   '("3" . meow-expand-3)
   '("2" . meow-expand-2)
   '("1" . meow-expand-1)
   '("-" . negative-argument)
   '(";" . meow-reverse)
   '("," . meow-inner-of-thing)
   '("." . meow-bounds-of-thing)
   '("[" . meow-beginning-of-thing)
   '("]" . meow-end-of-thing)
   '("a" . meow-append)
   '("A" . meow-open-below)
   '("b" . meow-back-word)
   '("B" . meow-back-symbol)
   '("c" . meow-change)
   '("d" . meow-delete)
   '("D" . meow-backward-delete)
   '("e" . meow-next-word)
   '("E" . meow-next-symbol)
   '("f" . meow-find)
   '("g" . meow-cancel-selection)
   '("G" . meow-grab)
   '("h" . meow-left)
   '("H" . meow-left-expand)
   '("i" . meow-insert)
   '("I" . meow-open-above)
   '("j" . meow-next)
   '("J" . meow-next-expand)
   '("k" . meow-prev)
   '("K" . meow-prev-expand)
   '("l" . meow-right)
   '("L" . meow-right-expand)
   '("m" . meow-join)
   '("n" . meow-search)
   '("o" . meow-block)
   '("O" . meow-to-block)
   '("p" . meow-yank)
   '("q" . meow-quit)
   '("Q" . meow-goto-line)
   '("r" . meow-replace)
   '("R" . meow-swap-grab)
   '("s" . meow-kill)
   '("t" . meow-till)
   '("u" . meow-undo)
   '("U" . meow-undo-in-selection)
   '("v" . meow-visit)
   '("w" . meow-mark-word)
   '("W" . meow-mark-symbol)
   '("x" . meow-line)
   '("X" . meow-goto-line)
   '("y" . meow-save)
   '("Y" . meow-sync-grab)
   '("z" . meow-pop-selection)
   '("'" . repeat)
   '("<escape>" . ignore)))

(use-package meow
  :config
  (meow-setup)
  (meow-global-mode 1))
